### ISSUE TITLE
Error when using credentials：Server selection timeout: No available servers

### ISSUE THREAD

**Issue by oraliuhui** [mongodb/mongo-rust-driver#543]
```
let mut client_options =
            ClientOptions::parse(format!("mongodb://{}:{}", prop.host, prop.port))
                .await
                .unwrap();
let credential: Credential = Credential::builder()
    .username(prop.username)
    .password(prop.password)
    .build();
client_options.credential = Some(credential);
let client = Client::with_options(client_options).unwrap();
for db_name in client.list_database_names(None, None).await.unwrap() {
      println!("{}", db_name);
}
```

**Comment by oraliuhui** [comment]
The same error when added mechanism, the parameters is correct, I used them in Robot3T:
```
let mut client_options =
            ClientOptions::parse(format!("mongodb://{}:{}", prop.host, prop.port))
                .await
                .unwrap();
let credential: Credential = Credential::builder()
    .username(prop.username)
    .password(prop.password)
    .mechanism(Some(AuthMechanism::ScramSha1))
    .build();
client_options.credential = Some(credential);
let client = Client::with_options(client_options).unwrap();
for db_name in client.list_database_names(None, None).await.unwrap() {
      println!("{}", db_name);
}
```

**Comment by patrickfreed** [comment]
So a server selection error often indicates that the driver couldn't connect to the deployment for one reason or another, and such an error shouldn't have anything to do with authentication. This could mean that it's not accessible (e.g. due to a firewall) or down. To help us debug this further, could you post the full error output that you see?

e.g. it should look something like this

```
Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Connection refused (os error 111) }, ] }
```

This example tells us that the server is refusing our connection because it's down.

Also, could you provide some details about your deployment. Is it a standalone/replicaset/sharded cluster? Is it on Atlas? Is it running on your local machine? Are you using TLS? What version of the server are you using? These details may further help us get to the bottom of this.

**Comment by realonbebeto** [comment]
Hello @patrickfreed, 

I need help with this error:

Error {
    kind: ServerSelection {
        message: "Server selection timeout: No available servers. Topology: { Type: Unknown }",
    },
    labels: {},
    wire_version: None,
    source: None,
    server_response: None,
}

I have a local MongoDB Docker setup, and the connection string is: mongodb://mongodb:mongodb@localhost:27017/mongo_store

Docker Compose setup:
```
  mongodb:
    container_name: mongodb
    image: mongo
    hostname: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MD_DB_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MD_DB_PASSWORD}
    ports:
      - "${MD_PORT}:${MD_PORT}"

    volumes:
      - "${MD_HOST_VOLUME}/init:/docker-entrypoint-initdb.d"
      - "${MD_HOST_VOLUME}/db:/data/db"
      - "${MD_HOST_VOLUME}/configdb:/data/configdb"
      - "${MD_HOST_VOLUME}/mongot:/data/mongot"

    restart: always
    network_mode: local
```



The code setup is:
```
let client_options = ClientOptions::parse(conn_str).await?;
let db_name = client_options.clone().default_database.unwrap();
let client = Client::with_options(client_options)?;
let db = client.database(&db_name);

let collections = db.list_collection_names().await?; // The happens on this line.
```
