### ISSUE TITLE
Memory leak in mongodb driver version 2.7

### ISSUE THREAD

**Issue by jakudlaty** [mongodb/mongo-rust-driver#978]
## Versions/Environment
1. rustc 1.73.0 (cc66ad468 2023-10-03) 
2. Gentoo Linux x64, on AMD Ryzen 5950
3. https://github.com/rust-lang/crates.io-index#mongodb@2.7.0
4. MongoDB version 7.0.2
5. Topology standalone
6. Empty database

## Describe the bug
Memory usage grows constantly on driver version 2.7, here is simple example program:
```rust
pub use mongodb::{Client};
use mongodb::bson::doc;
use mongodb::options::ClientOptions;
use serde::{Deserialize, Serialize};

type OrderId = String;

#[derive(Serialize, Deserialize, Clone)]
pub struct OrderEntity {
    #[serde(rename = "_id")]
    pub id: OrderId,
}

#[tokio::main]
async fn main() {
    let options = ClientOptions::parse("mongodb://localhost:27017/memleak?authSource=admin&ssl=false&maxpoolsize=20").await.unwrap();
    let client = Client::with_options(options).unwrap();
    let database = client.default_database().unwrap();
    let orders = database.collection::<OrderEntity>("Orders");

    for _ in 0..10000000 {
        let _result = orders.find_one(doc! {"_id" : "12345"}, None).await.unwrap();
    }
}
```
my Cargo.toml kools like this:
```toml
[package]
name = "mongo-memleak-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
mongodb = "=2.7.0"
```

The X axis on graph is measured in seconds

See the graph below:
![mem-graph-2 7](https://github.com/mongodb/mongo-rust-driver/assets/577430/106e2945-28be-4fc7-9493-b807916c8da0)

On version 2.6 memory looks perfectly fine:
![mem-graph-2 6](https://github.com/mongodb/mongo-rust-driver/assets/577430/de8e12d3-9571-4ec8-bf95-a5d160ffa03f)

Here is the full source code of working example https://github.com/jakudlaty/mongo-memleak-test/
